version: "3"
services:

  api-service:
    image: bohdanyakovlev/api-service:1.0.0
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8001"

  email-service:
    image: bohdanyakovlev/email-service:1.0.1
    depends_on:
      api-service:
        condition: service_started
    ports:
      - "8002:8002"

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "techuser"
      POSTGRES_PASSWORD: "techuser"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    ports:
      - "5432:5432"